import { AGGREGATE_FIELDS } from "../shared/model/constants";
import { DataCluster } from "../tasks/task.model";

export const addressFields: string[] = [
  'LEGAL_NAME',
  'NAME_ADDITION',
  'STREET',
  'STREET_NUMBER',
  'ADDRESS_ADDITION',
  'ZIP_CODE',
  'CITY',
  'DISTRICT',
  'STATE',
  'PROVINCE',
  'COUNTRY'
];

export const additionalAddressFields: string[] = [
  'ADDITIONAL_ADDRESS_STREET',
  'ADDITIONAL_ADDRESS_STREET_NUMBER',
  'ADDITIONAL_ADDRESS_ADDRESS_ADDITION',
  'ADDITIONAL_ADDRESS_ZIP_CODE',
  'ADDITIONAL_ADDRESS_CITY',
  'ADDITIONAL_ADDRESS_DISTRICT'
];

export const poBoxFields: string[] = [
  'PO_BOX_NUMBER',
  'PO_BOX_ZIP_CODE',
  'PO_BOX_CITY'
];

export const gpsFields: string[] = [
  'LATITUDE',
  'LONGITUDE'
];

export const baseDataAggregateFields = [
  AGGREGATE_FIELDS.BASE_DATA_ADDRESS_STREET,
  AGGREGATE_FIELDS.BASE_DATA_ADDRESS_NUMBER,
  AGGREGATE_FIELDS.BASE_DATA_ADDRESS_ADDRESS_ADDITION,
  AGGREGATE_FIELDS.BASE_DATA_ADDRESS_ZIP_CODE,
  AGGREGATE_FIELDS.BASE_DATA_ADDRESS_CITY,
  AGGREGATE_FIELDS.BASE_DATA_ADDRESS_DISTRICT,
  AGGREGATE_FIELDS.BASE_DATA_ADDRESS_STATE,
  AGGREGATE_FIELDS.BASE_DATA_ADDRESS_PROVINCE,
  AGGREGATE_FIELDS.BASE_DATA_NAME_ADDITION,
  AGGREGATE_FIELDS.BASE_DATA_ADDITIONAL_ADDRESS_STREET,
  AGGREGATE_FIELDS.BASE_DATA_ADDITIONAL_ADDRESS_STREET_NUMBER,
  AGGREGATE_FIELDS.BASE_DATA_ADDITIONAL_ADDRESS_ADDRESS_ADDITION,
  AGGREGATE_FIELDS.BASE_DATA_ADDITIONAL_ADDRESS_ZIP_CODE,
  AGGREGATE_FIELDS.BASE_DATA_ADDITIONAL_ADDRESS_CITY,
  AGGREGATE_FIELDS.BASE_DATA_ADDITIONAL_ADDRESS_DISTRICT,
  AGGREGATE_FIELDS.BASE_DATA_PO_BOX_NUMBER,
  AGGREGATE_FIELDS.BASE_DATA_PO_BOX_ZIP_CODE,
  AGGREGATE_FIELDS.BASE_DATA_PO_BOX_CITY,
  AGGREGATE_FIELDS.BASE_DATA_GPS_LATITUDE,
  AGGREGATE_FIELDS.BASE_DATA_GPS_LONGITUDE
]

export const baseDataDataClusters = [
  DataCluster.BASE_DATA_ADDITIONAL_ADDRESS,
  DataCluster.BASE_DATA_PO_BOX,
  DataCluster.BASE_DATA_GPS,
  DataCluster.BASE_DATA_NAME_ADDITION,
  DataCluster.BASE_DATA_STATE_AND_PROVINCE,
  DataCluster.BASE_DATA_ADDRESS_STREET,
  DataCluster.BASE_DATA_ADDRESS_NUMBER,
  DataCluster.BASE_DATA_ADDRESS_ADDRESS_ADDITION,
  DataCluster.BASE_DATA_ADDRESS_ZIP_CODE,
  DataCluster.BASE_DATA_ADDRESS_CITY,
  DataCluster.BASE_DATA_ADDRESS_DISTRICT,
  DataCluster.BASE_DATA_ADDRESS_STATE,
  DataCluster.BASE_DATA_ADDRESS_PROVINCE
]
