export const FEATURE_NAMES = {
  DOWNTIME_ADVANCE_NOTIFICATION: 'DOWNTIME_ADVANCE_NOTIFICATION',
  LINK_TO_SHAREHOLDER: 'LINK_TO_SHAREHOLDER',
  SERVICES_DISTRIBUTION_LEVEL_RESTRICTION: 'SERVICES_DISTRIBUTION_LEVEL_RESTRICTION',
  OUTLET_RELATIONSHIPS: 'OUTLET_RELATIONSHIPS',
  CONTRACT_PARTNER: 'CONTRACT_PARTNER',
  HISTORIZATION: 'HISTORIZATION',
  FOR_RETAIL_TASKS_TILE: 'FOR_RETAIL_TASKS_TILE',
  HISTORIZATION_MASTER_DATA: 'HISTORIZATION_MASTER_DATA',
  FOR_RETAIL: 'FOR_RETAIL'
};

export const AGGREGATE_NAMES = {
  COMPANY_LEGAL_INFO: 'CompanyLegalInfo',
  BUSINESS_SITE_LEGAL_INFO: 'BusinessSiteLegalInfo',
  COMPANY: 'Company',
  BUSINESS_SITE: 'BusinessSite',
  GENERAL_COMMUNICATION_DATA: 'GeneralCommunicationData',
  COMMUNICATION_CHANNELS: 'CommunicationChannels'
};

export const AGGREGATE_FIELDS = {
  LEGAL_INFO_TAX_NUMBER: 'taxNo',
  LEGAL_INFO_VAT_NUMBER: 'vatNo',
  LEGAL_INFO_LEGAL_FOOTER: 'legalFooter',
  BASE_DATA_ADDRESS_STREET: 'addressStreet',
  BASE_DATA_ADDRESS_NUMBER: 'addressStreetNumber',
  BASE_DATA_ADDRESS_ADDRESS_ADDITION: 'addressAddressAddition',
  BASE_DATA_ADDRESS_ZIP_CODE: 'addressZipCode',
  BASE_DATA_ADDRESS_CITY: 'addressCity',
  BASE_DATA_ADDRESS_DISTRICT: 'addressDistrict',
  BASE_DATA_ADDRESS_STATE: 'state',
  BASE_DATA_ADDRESS_PROVINCE: 'province',
  BASE_DATA_NAME_ADDITION: 'nameAddition',
  BASE_DATA_ADDITIONAL_ADDRESS_STREET: 'additionalAddressStreet',
  BASE_DATA_ADDITIONAL_ADDRESS_STREET_NUMBER: 'additionalAddressStreetNumber',
  BASE_DATA_ADDITIONAL_ADDRESS_ADDRESS_ADDITION: 'additionalAddressAddressAddition',
  BASE_DATA_ADDITIONAL_ADDRESS_ZIP_CODE: 'additionalAddressZipCode',
  BASE_DATA_ADDITIONAL_ADDRESS_CITY: 'additionalAddressCity',
  BASE_DATA_ADDITIONAL_ADDRESS_DISTRICT: 'additionalAddressDistrict',
  BASE_DATA_PO_BOX_NUMBER: 'poBoxNumber',
  BASE_DATA_PO_BOX_ZIP_CODE: 'poBoxZipCode',
  BASE_DATA_PO_BOX_CITY: 'poBoxCity',
  BASE_DATA_GPS_LATITUDE: 'gpsLatitude',
  BASE_DATA_GPS_LONGITUDE: 'gpsLongitude',
  COMMUNICATION_FIELDS: 'communicationField'
};

export const OUTLET_AGGREGATES = [AGGREGATE_NAMES.COMPANY, AGGREGATE_NAMES.BUSINESS_SITE];
export const LEGAL_INFO_AGGREGATES = [
  AGGREGATE_NAMES.COMPANY_LEGAL_INFO,
  AGGREGATE_NAMES.BUSINESS_SITE_LEGAL_INFO
];
export const GENERAL_COMMUNICATION_AGGREGATES = [AGGREGATE_NAMES.GENERAL_COMMUNICATION_DATA];
